/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'memo' : IDL.Text,
  'recipient' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getTransactionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'resetBalance' : IDL.Func([], [], []),
  'sendFlashTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'memo' : IDL.Text,
    'recipient' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getTransactionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'resetBalance' : IDL.Func([], [], []),
    'sendFlashTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };